events {}
http {
    server {
        listen 80;
        
        # Reverse proxy for MinIO public links (if enabled)
        location /media/ {
            proxy_pass http://minio:9000/media-processing/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Flower Monitoring
        location /flower/ {
            proxy_pass http://flower:5555;
            proxy_set_header Host $host;
        }
    }
}
